#!/bin/bash

count() {
	i=0
	while read line 
	do
		((i=i+1))
	done
	echo $i
}

loader() {
	if [[ $# -lt 1 ]]
	then 
		exit 2
	fi
	liter=0
	while [[ liter -lt $1 ]] do
		echo -n "#"
		((liter=liter+1))
	done
	while [[ liter -lt 10 ]] do
		echo -n " "
		((liter=liter+1))
	done
}


counter=$(transmission-remote -l | tr " " "\t" | cut -f6 | count)
((counter=counter-1))
((k=counter-1))

if [[ counter < 0 ]]
then
	echo "Counter < 0: exit 1" >&2
	exit 1
fi

transmission-remote -l | tr " " "\t" | cut -f6 | tail -n$counter | head -n$k | while read iter
do
	info=$(transmission-remote -t $iter -i | perl -ne "print if /Name/ xor /Percent/" | tr "\n" "\`" )
	perc=$(cut -d "." -f1 <<< $(cut -d "%" -f1 <<< $(cut -d ":" -f2  <<< $(echo $info | tr "\`" "\n" | grep "Percent Done:"))))
	name=$(echo $info | tr "\`" "\n" | grep "Name:")
	if [[ $perc -lt 100 ]]
	then
		if [[ $perc -lt 10 ]] then
			loading="          "
			space="  "
		else
			loading=$(loader ${perc:1:1})
			space=" "
		fi
		echo "$perc% $space[$loading] $name"
	else
		echo "$perc% [   done   ] $name"
	fi
	((iter=iter+1))
done
exit 0
